## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: MIT-0

apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: ncat-pool4
spec:
  replicas: 2
  strategy:
   type: Recreate
  template:
    metadata:
      labels:
        pool: FOUR
        region: ${AWS_REGION}
    spec:
      players:
      ports:
      - name: default
        protocol: TCP
        containerPort: 12345
      health:
       initialDelaySeconds: 30
       periodSeconds: 60
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: agones.dev/agones-gameserver
                    operator: Exists
          containers:
          - name: ncat
            args:
            - -p
            - "12345"
            image: ${REGISTRY}/agones-openmatch-ncat-server
            resources:
              requests:
                memory: "64Mi"
                cpu: "20m"
              limits:
                memory: "64Mi"
                cpu: "20m"
            securityContext:                 
              allowPrivilegeEscalation: false
              runAsNonRoot: true